-- PRYNTIX v2.0 — evolução segura do Financeiro
-- Execute uma única vez no SQL Editor do Supabase.

alter table public.contas_pagar add column if not exists numero_documento text;
alter table public.contas_pagar add column if not exists grupo_parcelas uuid;
alter table public.contas_pagar add column if not exists parcela_num integer default 1;
alter table public.contas_pagar add column if not exists parcelas_total integer default 1;
alter table public.contas_pagar add column if not exists comprovante_url text;
alter table public.contas_pagar add column if not exists data_pagamento date;
alter table public.contas_pagar add column if not exists valor_pago numeric(14,2) default 0;

create table if not exists public.contas_receber (
  id bigint generated by default as identity primary key,
  criado_em timestamptz not null default now(),
  cliente_id text,
  cliente_nome text not null,
  referencia text,
  forma_pagamento text not null default 'pix',
  valor numeric(14,2) not null check (valor > 0),
  situacao text not null default 'pendente' check (situacao in ('pendente','recebido','cancelado')),
  data_emissao date,
  data_vencimento date not null,
  grupo_parcelas uuid,
  parcela_num integer not null default 1,
  parcelas_total integer not null default 1,
  observacoes text
);

create table if not exists public.recebimentos (
  id bigint generated by default as identity primary key,
  criado_em timestamptz not null default now(),
  conta_receber_id bigint not null references public.contas_receber(id) on delete cascade,
  valor numeric(14,2) not null check (valor > 0),
  data_recebimento date not null default current_date,
  forma_pagamento text not null,
  comprovante_url text,
  observacoes text
);

create index if not exists idx_contas_pagar_vencimento on public.contas_pagar(data_vencimento);
create index if not exists idx_contas_pagar_fornecedor on public.contas_pagar(fornecedor_id);
create index if not exists idx_contas_receber_vencimento on public.contas_receber(data_vencimento);
create index if not exists idx_contas_receber_cliente on public.contas_receber(cliente_id);
create index if not exists idx_recebimentos_conta on public.recebimentos(conta_receber_id);

alter table public.contas_receber enable row level security;
alter table public.recebimentos enable row level security;

drop policy if exists "contas_receber_autenticados" on public.contas_receber;
create policy "contas_receber_autenticados" on public.contas_receber
for all to authenticated using (true) with check (true);

drop policy if exists "recebimentos_autenticados" on public.recebimentos;
create policy "recebimentos_autenticados" on public.recebimentos
for all to authenticated using (true) with check (true);

-- Garante acesso às novas colunas/tabelas pela API REST.
grant select, insert, update, delete on public.contas_receber to authenticated;
grant select, insert, update, delete on public.recebimentos to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- Link público seguro de orçamento (token imprevisível; sem SELECT anônimo na tabela).
alter table public.orcamentos add column if not exists public_token uuid not null default gen_random_uuid();
create unique index if not exists idx_orcamentos_public_token on public.orcamentos(public_token);

create or replace function public.get_orcamento_publico(p_token uuid)
returns jsonb language sql stable security definer set search_path = public as $$
  select jsonb_build_object(
    'orcamento', jsonb_build_object(
      'id', o.id, 'criado_em', o.criado_em, 'cliente', o.cliente,
      'cnpj_cli', o.cnpj_cli, 'solicitante', o.solicitante,
      'referencia', o.referencia, 'obs', o.obs, 'valido_ate', o.valido_ate,
      'itens', o.itens, 'desconto', o.desconto, 'tipo_desc', o.tipo_desc,
      'total', o.total, 'status', o.status
    ),
    'config', coalesce((select to_jsonb(c) - 'id' from public.config c limit 1), '{}'::jsonb)
  ) from public.orcamentos o where o.public_token = p_token limit 1;
$$;
revoke all on function public.get_orcamento_publico(uuid) from public;
grant execute on function public.get_orcamento_publico(uuid) to anon, authenticated;
